GET http://localhost:3000/users

###
GET http://localhost:3000/posts

###
GET http://localhost:3000/users/20

###
DELETE http://localhost:3000/users/5

###
// CREATE AN USER
POST http://localhost:3000/users/
Content-Type: application/json

{
  "firstname": "John",
  "lastname": "Doe",
  "email": "test3@test.com",
  "password": "2pass"
}


###
// CHANGING
PUT http://localhost:3000/users/20
Content-Type: application/json

{
  "lastname": "Do",
  "email": "test@test.com",
  "password": "lenouwo"
}

###
POST http://localhost:3000/register/
Content-Type: application/json

{
  "firstname": "John",
  "lastname": "Doe",
  "email": "test3@test.com",
  "password": "2pass"
}
